### ISSUE TITLE
Evaluation Function Interface

### ISSUE THREAD

**Issue by DavidThien** [DavidThien/IDE-IT#13]
Currently, there is no connection between the `BlockCommentEvaluator` or the `RemoveImportEvaluator`. There should be some sort of interface to represent the connection between these two and deal with some of the same functionality. Care should be taken when designing this interface because it's likely that different evaluators will care about different features of the document/eclipse.

**Comment by wahleric** [comment]
This issue has been addressed by https://github.com/DavidThien/IDE-IT/pull/19.
