### ISSUE TITLE
Proj05 Customer Feedback

### ISSUE THREAD

**Issue by elliottdebruin** [DavidThien/IDE-IT#16]
(1/1pt) I could find the instructions to build the project easily from the repository

I was able to find the instructions easily in your repository. One thing you could add to make the instructions even easier to find would be a table of contents at the top of your README.md file. This would allow your users to know exactly where to look for any details they need without needing to scroll until they find it. This also tells your user right away all the information they will be able to find by reading your README.md.

(1/1pt) I could reproduce the build on a machine matching the prerequisites mentioned in the instructions.

I was able to reproduce the build with a machine matching the prerequisites mentioned in the instructions.

(1/1pt) The instructions were clear and easy to use.

The instructions were clear and easy to use. I followed the instructions exactly and the build worked as expected. One suggestion would be to include the exact commands to build your project in the README. Including makes it much simpler for the user, as they would be able to just copy and paste the commands and be done.

(1/1pt) The continuous integration setup makes sense to me, and I could find the build history.

The CI setup makes sense. The build history is very easy to find since you have included a Travis CI badge at the top of your README. 

(1/1pt) The continuous integration history includes at least one failing test.

The continuous integration history includes multiple failing tests.

(1/1pt) The continuous integration history includes at least one passing test.

The continuous integration history includes multiple passing tests.

Other Notes:Reading over your proposal I think you could add quotes or statistics for some of the sources that you cite. For example, in your first paragraph you cite survey results that show developers only use a small number of IDE features and I think your point could be made stronger if the reader knows the exact results of the study. One other thing is you mention that your team is prioritizing five feature suggestions, but you do not go into depth on why you chose these specific features. I think it would be good to mention why you chose these features to implement over others. For example, do these five features show a broad range of how your tool can detect if a user could be using a feature that they are not currently.

**Comment by wahleric** [comment]
Thank you for the feedback. We have added a table of contents and more explicit command instructions to the manual. In the report, we have added a more specific example of feature usage statistics and explained our reasoning for the list of 5 features.
