### ISSUE TITLE
Project 5 Customer Feedback

### ISSUE THREAD

**Issue by cagesellchen** [DavidThien/IDE-IT#17]
Overall Score: 7/7
Great job! It was super straightforward to download and build your plugin. One comment is that after the "Building the Plugin" section, you say that the project needed to be cloned in an eclipse workspace. It would be helpful if you specified exactly where it should be cloned, and also you should mention this earlier. By the time I read it, I'd already followed the earlier instructions, and cloned it in a random place on my machine. 

(1pt) I could find the instructions to build the project easily from the repository
Yes - in the README

(1pt) I could reproduce the build on a machine matching the prerequisites mentioned in the instructions.
Yes - I didn't run into any problems

(1pt) The instructions were clear and easy to use.
Yes, although someone who doesn't have experience with git might have a hard time with the instructions. Perhaps give the commands (ex. git clone [repo]).

(1pt) The continuous integration setup makes sense to me, and I could find the build history.
Yes

(1pt) The continuous integration history includes at least one failing test.
Yes

(1pt) The continuous integration history includes at least one passing test.
Yes

**Comment by wahleric** [comment]
Thank you for the feedback. We have updated the manual instructions to add the git clone command and to be more explicit about importing the repository into the Eclipse workspace.
