### ISSUE TITLE
Customer feedback, Architecture

### ISSUE THREAD

**Issue by elliottdebruin** [DavidThien/IDE-IT#2]
(1/1 pt) The document builds on the original project proposal
Your proposal does build off of the previous version.
(1/1 pt) There is an architecture diagram
There is an architecture diagram but it could be refined. In the diagram you have input from the keyboard and mouse going to KeyPressTracker.java and MouseTracker.java respectively but the boxes in the diagram for these classes are not connected to anything else in the diagram. Do they pass along information or are they just stand alone features?
(1/1 pt) The architecture diagram is explained in English
You do explain the architecture diagram in english, but it is a little vague on how each component works and what the lines in-between boxes represent.
(1/1 pt) The system's interface is documented. (For graphical interfaces, a UI mockup should be included. For command-line interfaces, the document should explain how a user interacts with it. For components of larger systems, the document should explain how the component interacts with the system around it.)
This is the backend part of the team so there is not a graphical user interface. You do describe that other plugins will be able to use your tool to display tips using your IDE-IT, but is vague on how they will be able to do this and what the interface will be for them to incorporate their tips. It would be good to discuss exactly how third parties will be able to add features to IDE-IT.
(1/1 pt) The document contains discussion of tools and APIs that the team plans to use
The APIs you plan to use are discussed.

**Comment by johnbarUW** [comment]
The following are the updates made to the project report and implementation based off customer feedback:
- Refined diagram to more accurately depict information flow between classes
- Added explanations to classes listed in diagram to provide more details on functionality
- The user manual has more detailed instructions on how to install and use/interface with our plugin
- I agree it would be good to discuss how third parties will be able to add features to IDE-IT. That's a stretch goal to provide an easy way for others to add their own suggestions and we haven't spent much development time on.
