### ISSUE TITLE
Update Import Evaluation Functions

### ISSUE THREAD

**Issue by johnbarUW** [DavidThien/IDE-IT#22]
Following the discussions at the all team meeting, the following changes should be considered for both Remove Unused Imports and Auto Add Imports.

They should only be suggested on document saves.

Ideas -
1. We can pull all IMarkers from the entire project. IMarkers are only updated on project saves / builds. However, we will trigger notifications on documents that are not currently open (unless we special case for only open documents)

2. We can use document annotations and only trigger notifications on a document save. This will keep the notifications scoped to only open documents.

**Comment by wahleric** [comment]
Add Imports evaluator has been updated. All that's left is to update the Remove Unused Imports evaluator.

**Comment by johnbarUW** [comment]
Remove Unused Imports has been updated to check for unused imports throughout the entire Eclipse workspace (all open projects)
