### ISSUE TITLE
Proj06 Customer Feedback

### ISSUE THREAD

**Issue by OfekI** [DavidThien/IDE-IT#25]
(1/1) The report contains instructions to reproduce the results.

(0/3) I tried running both the "mvn -DTest..." command and the "python feature-stats.py" command. The mvn command failed to compile, citing "The method `getDisplay()` from the type `IWorkbench` refers to the missing type `Display`". I also could not successfully pip install "git" to run the python file (`Could not find a version that satisfies the requirement git`). Overall, I was not able to reproduce the results.

(1/2) The report discusses the results, but doesn't have much to say on what they mean about the project, its progress, and if there's any insights to be gleaned from it.

(1/1) The report looks pretty similar to before, but given the nature of the initial results I feel this is reasonable as it looks that the methodology hasn't changed.

(1/1) The schedule is updated to the current week. Mainly new checkmarks were added to mark the group's progress.

(2/2) The user manual contains instructions on how to reproduce the initial result.

The main thing I have to say is it looks like the initial results are kind of bare-bones. There is nothing to compare against when looking at them, so there is no understanding as to whether the tool is helpful or not (for the purpose it serves). Relative to the use cases this team has manually defined, there is a point of reference, but it is difficult to tell whether this really covers the most common use cases or not.

**Comment by wahleric** [comment]
Thanks for the feedback, we've updated our manual to provide more explicit instructions for getting the Python file
