### ISSUE TITLE
Project 6 Customer Feedback

### ISSUE THREAD

**Issue by cagesellchen** [DavidThien/IDE-IT#26]
Overall you guys did a good job on this! Some of the instructions in your user manual need to be updated, and I didn't seem to have permission for your tests. You discuss the results of your tests, but not what you learned for them, which I think would be a valuable addition. I also think that having a "real" user test would be more valuable. It looks like you're testing various keystrokes to test that your plugin suggests the correct hotkey/solution, which is great for a test suite, but I think for next time you'd gain a lot more from seeing a real person interact with your plugin. They might do something in a way you didn't anticipate. 

(0.5/1 pt) The report or the README contains instructions to reproduce the initial results.
I wasn't able to install the plugin based on your instructions. When I ran "mvn clean install" I got the following error: "The goal you specified requires a project to execute but there is no POM in this directory (/Users/retina/Documents/University of Washington/CSE 403/IDE-IT). Please verify you invoked Maven from the correct directory." I was however able to install it by running "mvn clean install" from your backend_plugin folder, so I'm guessing you just forgot to update the user manual.

(1/3 pts) The initial results are reproducible.
I'm able to run "mvn -Dtest=*Negative surefire-report:report" successfully. However, if I try to run runTestCases.sh (./runTestCases.sh), I get the following error: "-bash: ./runTestCases.sh: Permission denied". Additionally, when I try to run "python feature-stats.py", I get the following error:

"Traceback (most recent call last):
  File "feature-stats.py", line 1, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'"

(1.5/2 pts) The report has a discussion of the results.
Yes, you show and discuss the results of your user test. One area for improvement is that you don't talk about what your initial results tell you about the status of your project, or how they influence your design. For example, do the results show any bugs that you need to fix, or weaknesses in your design? 

(1/1 pt) The report expands on the methodology and is complete.
Yes. 

(1/1 pt) The schedule is updated and there is a reasonable discussion on why it changed.
Yes - It looks like you're checking off completed tasks and updating your schedule regularly.

(2/2 pts) The user manual is updated.
Yes, the user manual has been updated, but some of the instructions need to be updated.

**Comment by wahleric** [comment]
Thanks for the feedback! We have updated the user manual and are working on fixing the issues with the python script.
