### ISSUE TITLE
Draft Final Report Feedback

### ISSUE THREAD

**Issue by elliottdebruin** [DavidThien/IDE-IT#37]
(1pt) overall organization is sensible
The organization is good and makes logical sense. The sections that require the reader to have knowledge of other sections are placed later on and in a good order that keeps the reader engaged.
(1pt) introduction motivates the problem and describes the approach
The introduction covers the motivation for the problem and describes the general approach for your solution which is good to get the reader intrigued, and then you go into more detail later on. 
(1pt) the technical details of the approach are well-described
The technical details are well described.
(1pt) the report contains a clear description of a reproducible methodology
The report does contain a clear description for the evaluation methodology and it would be able to be reproduced.
(1pt) results are presented clearly and described in text
The results are presented clearly and are described. I also like that you go into detail about the research and tests you plan to conduct in the future.
(1pt) the report describes related work and contains academic references
You do a good job of addressing related work and describing why your solution is unique. There are also many academic references.

Other Notes:
In your evaluation you say that your main goal in testing is to reduce the number of false negatives, however the graph shown is a graph representing when your tool is performing correctly. I think this is still a good graph to show, but I also think you should have a visual for your data on false negative results since that is your main focus. One other note is you mention that some changes could be hard to track due to users using shortcuts or other plugins. Does this mean they are using the shortcuts and other plugins instead of the Eclipse features you would suggest or does it mean that them using other shortcuts and plugins interfere with your suggestions? I think a bit more detail on this point would be good. It could also be good to give a sentence or two on the limitations of your tool. Are there any Eclipse features that you would not be able to detect if a user could be in need of it or can you make a suggester for every feature, given enough time?

**Comment by wahleric** [comment]
Thank you for the feedback! We are working to improve our evaluation section, and the part about using shortcuts and other plugins was left over from an earlier iteration of our report; it has now been removed.
