### ISSUE TITLE
Proj 7 Customer Feedback

### ISSUE THREAD

**Issue by cagesellchen** [DavidThien/IDE-IT#38]
Great job! Overall your report is complete and well written. The only real feedback I have is to improve your Initial Results section by describing the importance of the tests, and what they tell you about how you can improve your project. You show the graph, but never really discuss what that specific graph is telling you, and how you can use it to improve your product. You do a good job of having tests that show your project is improving over time, but you don't seem to have tests (such as a usability test) that show weaknesses in your plugin.

**(1/1pt) overall organization is sensible**
Yes, your organization makes sense.

**(1/1pt) introduction motivates the problem and describes the approach**
Yes, I found the introduction compelling, and you describe your approach at a high level. 

**(1/1pt) the technical details of the approach are well-described**
Yes, all of your Architecture section is clear and comprehensive. 

**(1/1pt) the report contains a clear description of a reproducable methodology**
Yes, you have mock user tests that can be run through runTestCases.sh, and you link to your repo where instructions can be found on how to reproduce these results. However, I think having a real usability test would be extremely helpful, because mock tests will only notify you of issues that you've already foreseen, whereas a user test could reveal something new about your project.

**(1/1pt) results are presented clearly and described in text**
You discuss how your tests work, and you have a graph showing that the tests you've written are working, but you don't ever describe what this graph tells you, or how it can help you improve your product. I think it would be beneficial to discuss the importance of the tests in regards to product improvement.

**(1/1pt) the report describes related work and contains academic references**
Yes, you describe related work in the "Related Works" section, and you have academic references for both that and sources used in your "Motivation" section.

**Comment by wahleric** [comment]
Thank you for the feedback! We are working to improve our evaluation section in particular.
