### ISSUE TITLE
Project 8a Customer Feedback

### ISSUE THREAD

**Issue by KamdenChew** [DavidThien/IDE-IT#49]
Customer Feedback Summary: 
Your repository is in great shape, your code and results are well-documented, and your results matched what you said they should be. Great work!

Customer Feedback Rubric:
(4 pts) You can follow the instructions to reproduce the results in the paper: 4
Building was successful with the instruction you provided. After changing to the specified directory, we ran your bash script. Your bash script produced the .html file that you specified and gave us information on your tests, including error rates, skips, failures, and success rates.

(2 pts) These instructions are fully automated: 2
The results didn’t require much thought to produce. All we had to do was move into a directory, run one command to build, and run one command to produce results.

(4 pts) The code and experimental results are well documented: 4
The code was well documented, even the test files. The results were located exactly where you said they’d be, and provide a lot of insight into what test cases you run, and things like error rates, total tests, failures, skips, success rates, time taken, etc. It’s also good that you mention in your paper that your evaluative techniques are based on what your team deems to be proper behavior (when it’s appropriate to notify) because there is some subjectivity to the tests you use.

**Comment by wahleric** [comment]
Thank you for the feedback!
