### ISSUE TITLE
Customer feedback, User Manual

### ISSUE THREAD

**Issue by elliottdebruin** [DavidThien/IDE-IT#6]
(1pt) The document builds on the previous submission

- The report seems similar or identical to the report from the week before

(1pt) There is a user manual and I could find it easily on the repo

- The user manual is easy to find on the first page on the GitHub repository.

(1pt) The user manual is self contained and well documented

- The user manual is not self contained. A user that wants to create a front-end interface for your tool only needs the usage section to learn what they need to create a front-end. The user does not need the implementation details section of your user manual. The implementation details and architecture diagram is for the audience of your proposal. 
- As an API document, the usage of each parameter and the possible output from return should be specified more clearly. Currently the document is nothing more than abstractions.

(1pt) The user manual contains all instructions required to use the tool

- The user manual looks like it contains everything a new user would need to integrate it with their front-end plugin.

(1pt) The report contains clear implementation details

- The report does contain an architecture diagram detailing the responsibilities of each module of the system and the implementation details are clear and understandable.

(1pt) The team's plans are clear and measurable

- The team’s plans are clear, but not all of them are easily measurable (or they don’t state their threshold for success). Items such as “Include additional feature evaluations” and “Should have an almost fully functional plugin” don’t provide a way to determine whether these goals were met or not.

Suggestions:
The only input that the backend is passing to the frontend is the FeatureID String. This will allow the frontend to display the relevant tip at the correct time. This is good for providing the user a new tip that they could be using at that time but you are not passing any more information to the frontend to allow them to show the user why this tip is being displayed. We think it would be useful for the frontend to have to ability to highlight or somehow show the user what they did and on which lines of code that caused the tip to be triggered. This would allow the user to know exactly what they were doing that the tip can replace.

Another note is you have a “Future Plans” section, but everything in this section is discussed in more detail in the Usage section so we do not think the “Future Plans” section is necessary. The user manual is supposed to reflect a manual for your finished project so you should include everything you plan to have in the finished product.

**Comment by wahleric** [comment]
We have implemented the following changes from this feedback:

- Made adjustments to the plans/goals of the report to make milestones more clear/concrete
- Removed "Future Plans" section, and instead created a "Current Status" section section per TA's suggestion
-Rewrote "Usage" section to be more explicit in terms of instructions and possible inputs to the notify(String) method of the FeatureSuggestionObserver
-Improved the implementation diagram to show more detailed information about the information passed between classes

We did not make any changes based on the following feedback:

-Removing implementation details from manual: We may end up modifying this section, but this is something we would like to discuss with our TA on Thursday to clarify
-Including additional information in what is passed to the frontend through the interface: This is an interesting idea, but the implementation would be tricky and may be out of the scope of what we can reasonably hope to accomplish in the time span of this course. If we have additional time, we may look into this.
